settings: Prevent bogus Python 3.5 error
Python 3.5 fails with:

SyntaxError: only named arguments may follow *expression

which is a rule only for function declaration, not for function call.